# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=5, unique=True)),
                ('title', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=8)),
                ('service_class', models.CharField(max_length=3)),
                ('name', models.TextField(max_length=20)),
                ('date_active', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Route')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('schedule_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.ScheduleClass')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(db_index=True)),
                ('title', models.TextField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Route')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledarrival',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Stop'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='scheduled_arrival_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.ScheduledArrival'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Stop'),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together=set([('tag', 'route_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleclass',
            unique_together=set([('route_id', 'direction', 'service_class')]),
        ),
    ]
