# Generated by Django 2.0.8 on 2018-12-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('difference', models.IntegerField()),
            ],
            options={
                'db_table': 'arrival',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=5, unique=True)),
                ('title', models.TextField(max_length=40)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='ScheduleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=8)),
                ('service_class', models.CharField(max_length=3)),
                ('name', models.TextField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_class', to='worker.Route')),
            ],
            options={
                'db_table': 'schedule_class',
            },
        ),
        migrations.CreateModel(
            name='ScheduledArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'scheduled_arrival',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(db_index=True, unique=True)),
                ('title', models.TextField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop', to='worker.Route')),
            ],
            options={
                'db_table': 'stop',
            },
        ),
        migrations.CreateModel(
            name='StopScheduleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField()),
                ('schedule_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_schedule_class', to='worker.ScheduleClass')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_schedule_class', to='worker.Stop')),
            ],
            options={
                'db_table': 'stop_schedule_class',
            },
        ),
        migrations.AddField(
            model_name='scheduledarrival',
            name='stop_schedule_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_arrival', to='worker.StopScheduleClass'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='scheduled_arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival', to='worker.ScheduledArrival'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Stop'),
        ),
        migrations.AlterUniqueTogether(
            name='stopscheduleclass',
            unique_together={('stop', 'schedule_class', 'stop_order')},
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('tag', 'route')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduledarrival',
            unique_together={('stop_schedule_class', 'block_id', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleclass',
            unique_together={('route', 'direction', 'service_class')},
        ),
        migrations.AlterUniqueTogether(
            name='arrival',
            unique_together={('stop', 'scheduled_arrival', 'time')},
        ),
    ]
